version: '2'

networks:
  snoozraft:

services:
  bootstrap1:
    image: snoozraft:latest
    environment:
      SNOOZ_BOOTSTRAP: "Y"
      SNOOZ_HOST: "boostrap1"
      SNOOZ_PORT: "5678"
      SNOOZ_CLIENT_PORT: "4444"
      SNOOZ_BOOTSTRAP_NODES: "tcp://bootstrap1:5678"
    ports:
      - 4444:4444
    networks:
      - snoozraft

  peer1:
    image: snoozraft:latest
    environment:
      SNOOZ_HOST: "peer1"
      SNOOZ_PORT: "5678"
      SNOOZ_CLIENT_PORT: "4444"
      SNOOZ_BOOTSTRAP_NODES: "tcp://bootstrap1:5678"
    ports:
      - 4445:4444
    networks:
    - snoozraft

  peer2:
    image: snoozraft:latest
    environment:
      SNOOZ_HOST: "peer2"
      SNOOZ_PORT: "5678"
      SNOOZ_CLIENT_PORT: "4444"
      SNOOZ_BOOTSTRAP_NODES: "tcp://bootstrap1:5678"
    ports:
      - 4446:4444
    networks:
      - snoozraft